export const industries: string[] = [
    'Aerospace',
    'Agriculture',
    'Automotive',
    'Biotechnology',
    'Chemicals',
    'Construction',
    'Consumer Goods',
    'Defense',
    'Education',
    'Energy',
    'Entertainment',
    'Financial Services',
    'Food & Beverage',
    'Healthcare',
    'Hospitality',
    'Information Technology',
    'Insurance',
    'Logistics',
    'Manufacturing',
    'Media',
    'Mining',
    'Non‑profit',
    'Oil & Gas',
    'Pharmaceuticals',
    'Professional Services',
    'Real Estate',
    'Retail',
    'Telecommunications',
    'Transportation',
    'Utilities',
    'Waste Management',
    'Wholesale',
];
